In [2]:
import pandas as pd

from multiprocessing import Pool
from concurrent.futures import ProcessPoolExecutor
import string
from bs4 import BeautifulSoup

# import boto3
import numpy as np

import json
import os
import time


ApplicationIntent="ReadOnly"
server="172.16.0.218"
database="Spatialrss"
username='RDUBSU6KMWWn3DQZNNzG_AI_Application'
password='>\Wt<C}H&[$222TEp`5krrZ```'
import pyodbc
conn = pyodbc.connect(
            'DRIVER={ODBC Driver 17 for SQL Server};SERVER=' + server + ';DATABASE=' + database + ';UID=' + username + ';PWD=' + password + ';ApplicationIntent=' + ApplicationIntent)
conn.setencoding(encoding="utf-8")
conn.setdecoding(pyodbc.SQL_CHAR, encoding="utf-8")
conn.setdecoding(pyodbc.SQL_WCHAR, encoding="utf-8")

In [3]:
def new_func(categoryname, brandid):
    q1 = f"""Select MAIN1.BrandID as Brandid, Ait.Response_Text as ResponseGenie,Main.Description as AgentReply
 From  {categoryname}.dbo.Tag_{categoryname} MAIN1 WITH(NOLOCK)
 Left Join {categoryname}.dbo.Tag_{categoryname} MAIN WITH(NOLOCK) on MAIN1.BrandID = MAIN.BrandID  
AND (Case when MAIN.ChannelGroupID in (7) Then Convert(Varchar(200),MAIN.PostID) ELSE Main.PostSocialID END)
    =(Case when MAIN1.ChannelGroupID in (7) Then MAIN1.ObjectID ELSE MAIN1.TweetIDorFbid  END) AND MAIN.IsBrandPost=1
LEFT OUTER JOIN {categoryname}.dbo.mstAISuggestedTokenDetails Ait WITH(Nolock) on  Ait.TagID=Main1.Tagid
Where MAIN1.IsBrandPost=0  AND MAIN1.ExistingTagID>0 
AND MAIN1.BrandID= {brandid}  
AND MAIN1.CreatedDate >='2023-09-24 18:30:00' AND MAIN1.CreatedDate <='2023-09-27 18:29:59'  """
    ans = pd.read_sql(q1, conn)
    return ans

In [4]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')


def calculate_sentence_similarity(sentence1, sentence2):
    # Encode the sentences into embeddings
    embedding1 = model.encode(sentence1, convert_to_tensor=True)
    embedding2 = model.encode(sentence2, convert_to_tensor=True)

    # Calculate cosine similarity
    cosine_similarity = util.pytorch_cos_sim(embedding1, embedding2)

    return cosine_similarity.item()

/home/user/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
def operations(df):
    # drop duplicates
    df = df.drop_duplicates()
    # drop na from AgentReply
    df = df.dropna(subset=['AgentReply'])
    # drop na from ResponseGenie
    df = df.dropna(subset=['ResponseGenie'])
    # remove twitter handles
    df['ResponseGenie'] = df['ResponseGenie'].str.replace(r'@\w+', '', regex=True)
    df['AgentReply'] = df['AgentReply'].str.replace(r'@\w+', '', regex=True)
    # remove #tages
    df['ResponseGenie'] = df['ResponseGenie'].str.replace(r'#\w+', '', regex=True)
    df['AgentReply'] = df['AgentReply'].str.replace(r'#\w+', '', regex=True)
    # Remove punctuation
    df['ResponseGenie'] = df['ResponseGenie'].str.replace(f'[{string.punctuation}]', '', regex=True)
    df['AgentReply'] = df['AgentReply'].str.replace(f'[{string.punctuation}]', '', regex=True)
    return df

In [6]:
res = new_func("TataDigitalDb", 6954)

/tmp/ipykernel_364789/163993027.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ans = pd.read_sql(q1, conn)

In [7]:
res

,Brandid,ResponseGenie,AgentReply
0,6954,"""Dear Rahul, In order to continue with the app...","@imupadhyay Hi Rahul Upadhyay, thank you for c..."
1,6954,"""Dear Rahul, In order to continue with the app...",@imupadhyay Hi Rahul. we wish to advise you th...
2,6954,"""Hi Sri Mahesh S, \nWe apologize for the incon...","Hi, we're disappointed to hear this. We reques..."
3,6954,"""I apologize for the inconvenience you have fa...","Hi, we're disappointed to hear this. We reques..."
4,6954,"""I am sorry to hear that you are having diffic...","Hi, we're disappointed to hear this. We reques..."
...,...,...,...
76465,6954,None,None
76466,6954,None,None
76467,6954,None,None
76468,6954,None,None
76469,6954,None,None

In [8]:
res = operations(res)

In [9]:
res

,Brandid,ResponseGenie,AgentReply
0,6954,Dear Rahul In order to continue with the appli...,Hi Rahul Upadhyay thank you for contacting TA...
1,6954,Dear Rahul In order to continue with the appli...,Hi Rahul we wish to advise you that in order ...
2,6954,Hi Sri Mahesh S \nWe apologize for the inconve...,Hi were disappointed to hear this We request y...
3,6954,I apologize for the inconvenience you have fac...,Hi were disappointed to hear this We request y...
4,6954,I am sorry to hear that you are having difficu...,Hi were disappointed to hear this We request y...
...,...,...,...
9166,6954,We are delighted to receive your positive feed...,Hi were disappointed to hear this We request y...
9167,6954,Thank you for rating our service We value your...,Hi were disappointed to hear this We request y...
9171,6954,Hi Riya we apologize for the inconvenience you...,Hi were disappointed to hear this We request y...
9174,6954,We understand your frustration and apologize f...,Hi Avishek please accept our sincere apologie...
9179,6954,Hi there Its great to hear that you are enjoyi...,Hi were disappointed to hear this We request y...

In [ ]:
score = []
for i, j in zip(res["ResponseGenie"].values, res["AgentReply"].values):
    score.append(calculate_sentence_similarity(str(i), str(j)))
res["score"] = score

In [ ]:
res